name: flutter_appodeal
description: A Flutter plugin for Appodel SDK
version: 0.3.0
author: Daniel Alejandro forked from Jordan Lewis <dev_jordanlewis at icloud.com>
homepage: https://github.com/jjlewis/flutter_appodeal

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.divertap.flutter.flutterappodeal
    pluginClass: FlutterAppodealPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
